### ISSUE TITLE
Send Authorization-Email

### ISSUE THREAD

**Issue by strukturart** [bnomei/kirby-instagram-api#7]
Hello,

when I send in the panel the Authorization Mail I get an error: error Bad request
What am I doing wrong ?

**Comment by strukturart** [comment]
Where can I set this  ?

> Before triggering any emails make sure you sending email is correct by setting either plugin.instagram-api.email.from or email.from.

**Comment by bnomei** [comment]
settings are done in kirby config file. 

https://getkirby.com/docs/developer-guide/configuration/options

also make sure to use a server online not localhost. orherwise instagram can not respond.

**Comment by strukturart** [comment]
@bnomei 
yes the webpage is online not on localhost
---
my /site/config.php
```
c::set('plugin.instagram-api.client-id', 'xxx19c78');
c::set('plugin.instagram-api.client-secret', 'cxxx53');
c::set('email.service', 'mail');
c::set('email.from', 'mypage <info@mypage.com>');
c::set('email.replyTo', 'mypage <info@mypage.com>');
c::set('email.subject', 'mypage');
```

it is right ?

**Comment by bnomei** [comment]
like specified [here](https://getkirby.com/docs/cheatsheet/helpers/email) you can add an display name for the email address. the plugin did not allow this yet. I fixed it with [0.9.2](https://github.com/bnomei/kirby-instagram-api/releases/tag/v0.9.2-beta). 

please download again or use [kirby cli](https://github.com/getkirby/cli):
```
kirby plugin:update bnomei/kirby-instagram-api
```

also consider **not** setting `email.service` so *kirby-instagram-api* plugin can use [its html-enabled email service](https://github.com/bnomei/kirby-instagram-api/blob/master/kirby-instagram-api.php#L236) (or provide your own).

**Comment by strukturart** [comment]
@bnomei 
sorry or my questions but i'am not a  not very experienced coder 

my /site/config:

```

c::set('plugin.instagram-api.client-id', 'xxx');
c::set('plugin.instagram-api.client-secret', 'xxx');
c::set('plugin.instagram-api.license', 'xxx');
```

updated the plugin
in the Panel Send Authorization-Email Error still: _errorBad request_

What must I set in instagram managed clients -> security -> Valid redirect URIs ?

**Comment by bnomei** [comment]
you have to set whatever server you are using to trigger the request (via the instagram plugin in the panel) plus `kirby-instagram-api/redirect`.

Example
- server: `http://www.strukturart.ch`
- panel: `http://www.strukturart.ch/panel`
- *redirect uri* in instagram: `http://www.strukturart.ch/kirby-instagram-api/redirect`

if your panel url does not have `www.` then remove that in the *redirect uri* as well.

https://github.com/bnomei/kirby-instagram-api#setup-instagram-client-security

**Comment by strukturart** [comment]
what can I do to solve this problem ?
in the Panel Send Authorization-Email Error still: errorBad request

**Comment by strukturart** [comment]
can be that the problem ?
https://www.instagram.com/developer/review/

i'am in still in sandbox modus

**Comment by bnomei** [comment]
**sandbox**
the plugin will work in sandbox mode too. if you invite the users (up to 10) and they agree.

**sending emails**
apart from the plugin having another problem it could mean that your server will not send the email. I will think about a solution to improve the error message. 

meanwhile please verify if your server will send emails from `email.from` at all. 

1) most servers do not allow sending emails from different domains. so if your server is `strukurart.ch` the from email must be something like `noreply@strukturart.ch`.

2) please add this code to a template you can access (like the *default* in `/site/templates/default.php`).

it will send an email to whatever email-address you set at your config file.

```php
<?php
$email = email(array(
  'to'      => c::get('email.from'), // or 'my@email.ch'
  'from'    => c::get('email.from'),
  'subject' => 'Sending emails with Kirby is easy',
  'body'    => 'Hey! This was really easy!'
));

if($email->send()) {
  echo 'The email has been sent';
} else {
  echo $email->error();
}
?>
```

**Comment by strukturart** [comment]
**sandbox**
it is a must invite 10 users ?

**mail**
error output : Invalid User Invalid recipient

**Comment by bnomei** [comment]
**sandbox**
the instagram account creating the app (even a sandboxed one) is added by default. you can but do not have to add additional accounts to participate in the sandbox. so you *must not* invite more but should if the account you want to access with the api is not the same as the one creating the app.

Example
- account `strukturart` creates a sandbox app on instagram
- this plugin should display images from account `friendofperry`.
- then `friendofperry` must be invited into the sandbox.

**email**
this means there is something else wrong. are you sure the config is loaded? try echoing the value from the config as well.

```php
<?php echo c::get('email.from'); ?>
```

**Comment by strukturart** [comment]
**sandbox**
It is my own account

**email**

```
<section>
  hello instagram
  <?php snippet('ia-example-media'); ?>
  <?php echo c::get('email.from'); ?>
</section>

```
output:
_Invalid User._

**full "config**

```
<?php



c::set('license', 'xx');
c::set('debug', true);

c::set('plugin.instagram-api.client-id', 'xxx');
c::set('plugin.instagram-api.client-secret', 'xx');
c::set('plugin.instagram-api.license', 'xx');




c::set('languages', array(
  array(
    'code'    => 'en',
    'name'    => 'en',
    'default' => true,
    'locale'  => 'en.utf-8',

    'url'     => '/',
  ),
    array(
    'code'    => 'fr',
    'name'    => 'fr',
    'locale'  => 'fr.utf-8',
    'url'     => '/fr',
  ),
     array(
    'code'    => 'de',
    'name'    => 'de',
    'locale'  => 'de.utf-8',
    'url'     => '/de',
  )
));

/*
---------------------------------------
Kirby Configuration
---------------------------------------

By default you don't have to configure anything to
make Kirby work. For more fine-grained configuration
of the system, please check out http://getkirby.com/docs/advanced/options

*/

```

**Comment by bnomei** [comment]
you still need to add at least`email.from` to the config. the domain of server should match the email domain – `mypage.com` and `info@mypage.com`.

```php
c::set('email.from', 'mypage <info@mypage.com>');
```

**Comment by strukturart** [comment]
must be the kirby user name == instagram user name ?

**Comment by bnomei** [comment]
> must be the kirby user name == instagram user name ?

no.

**Comment by strukturart** [comment]
oh yes !!
---
now the **Send Authorization-Email** works
---
It is right my client gets an e-mail with an authorization link ?

**Comment by bnomei** [comment]
the email-adress of the kirby user (your client i presume) got the verification-link email (from `email.from`). 
now they need to verify the access in clicking the link. their instagram account must be default of sandbox or added (and accepted) before that.

**Comment by strukturart** [comment]
@bnomei 
thank you for  your time now it works
^..^

**Comment by bnomei** [comment]
sure. :-)
